#!/usr/bin/env python3

# Calculate how long an rsync ran based on the log file
# Expects input from STDIN of the form:
#
# 2017/11/02 18:37:30 building file list
# 2017/11/03 08:35:48 Files  56561
# 2017/11/03 08:35:48 Size   5774.78G bytes
# 2017/11/03 08:35:48 sent 5775488914881 bytes  received 1082071 bytes  total size 5808105402616
#
# Which is generated by the "rsync_log" function

from datetime import datetime
import sys
import re

start = None
end = None

for line in sys.stdin:
	timestamp = " ".join(line.split()[:2])
	if re.search("building file list", line):
		start = timestamp
	if re.search("total size", line):
		end = timestamp

if start and end:
	start = datetime.strptime(start, "%Y/%m/%d %H:%M:%S")
	end = datetime.strptime(end, "%Y/%m/%d %H:%M:%S")
	duration = end - start
	print("{0:.1f} hrs".format(duration.total_seconds() / 3600))
else:
    # if the log is not yet finished, prepend a ">"
	start = datetime.strptime(start, "%Y/%m/%d %H:%M:%S")
	last = datetime.strptime(timestamp, "%Y/%m/%d %H:%M:%S")
	duration = last - start
	print(">{0:.1f} hrs".format(duration.total_seconds() / 3600))
